### ISSUE TITLE
尝试切换到GPT-4o，但使用的继续是GPT-4 Turbo

### ISSUE THREAD

**Issue by cobaltdisco** [egoist/chatkit-desktop#4]
**基本信息**
- 设备型号：M1 Max MacBook Pro
- 系统版本：macOS 14.4.1
- ChatKit版本：Version 0.3.23 (0.3.23)

**复现过程**
1. 打开ChatKit的Mac桌面版
2. 选择GPT-4o
3. 测试对话，并直接询问是否是GPT-4o，模型回答不是，是GPT-4 Turbo
4. 同时查看OpenAI API使用记录后台，发现使用的是GPT-4-turbo-2024-04-09

**Comment by egoist** [comment]
我测试了下是正常用的 4o，4o 的速度至少比 turbo 快 2 倍，你看速度有没有区别

**Comment by cobaltdisco** [comment]
> 我测试了下是正常用的 4o，4o 的速度至少比 turbo 快 2 倍，你看速度有没有区别

测试了下，发现生成速度的确快不少……然后目前也看到后台使用记录的是GPT-4o-2024-05-13了。

感觉可能是之前后台延迟显示的问题，导致了我误以为继续使用的是Turbo。那么没其他问题了，感谢！

**Comment by egoist** [comment]
好的

> 测试对话，并直接询问是否是GPT-4o，模型回答不是，是GPT-4 Turbo

用这个测试一般都不管用，只会回答是基于 gpt-4 的
